repos:

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
      files: '.*py'
      exclude: '^tools'

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.280'
    hooks:
      - id: ruff
        args: ["--config", "pyproject.toml", "--fix", "--fix-only", "--show-fixes"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.3.0'
    hooks:
    - id: mypy
      additional_dependencies: [types-all]
      exclude: ^tests/

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: ['--check-only']
      additional_dependencies: ['toml']
      exclude: '^tools'

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
      args: ['--check']
      exclude: '^(projects/tools)'
